<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260323143958 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ai_batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_batch_id VARCHAR(255) DEFAULT NULL, provider VARCHAR(32) NOT NULL, task VARCHAR(64) NOT NULL, dataset_key VARCHAR(255) DEFAULT NULL, status VARCHAR(32) NOT NULL, input_file_path VARCHAR(255) DEFAULT NULL, input_file_id VARCHAR(255) DEFAULT NULL, output_file_id VARCHAR(255) DEFAULT NULL, error_file_id VARCHAR(255) DEFAULT NULL, request_count INT NOT NULL, completed_count INT NOT NULL, failed_count INT NOT NULL, estimated_cost_usd NUMERIC(10, 6) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_polled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, applied_count INT NOT NULL, meta JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4BC69917B00651C ON ai_batch (status)');
        $this->addSql('CREATE INDEX IDX_A4BC699192C4739C7B00651C ON ai_batch (provider, status)');
        $this->addSql('CREATE TABLE ai_batch_result (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ai_batch_id INT NOT NULL, custom_id VARCHAR(191) NOT NULL, success BOOLEAN NOT NULL, content JSON DEFAULT NULL, error TEXT DEFAULT NULL, prompt_tokens INT NOT NULL, output_tokens INT NOT NULL, raw JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B236ECDEC78381A ON ai_batch_result (ai_batch_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ai_batch_result ON ai_batch_result (ai_batch_id, custom_id)');
        $this->addSql('CREATE TABLE batch_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_batch_id VARCHAR(191) NOT NULL, task VARCHAR(64) NOT NULL, model VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, request_count INT NOT NULL, processed_count INT NOT NULL, failed_count INT NOT NULL, output_file_id VARCHAR(191) DEFAULT NULL, error_file_id VARCHAR(191) DEFAULT NULL, meta JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_polled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, results_path VARCHAR(255) DEFAULT NULL, results_fetched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_batch_run_provider_batch_id ON batch_run (provider_batch_id)');
        $this->addSql('CREATE TABLE postcard (id VARCHAR(64) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, thumbnail_url TEXT DEFAULT NULL, iiif_manifest TEXT DEFAULT NULL, iiif_base TEXT DEFAULT NULL, country VARCHAR(128) DEFAULT NULL, state VARCHAR(128) DEFAULT NULL, city VARCHAR(128) DEFAULT NULL, subject_facet JSON NOT NULL, subject_geographic JSON NOT NULL, raw_data JSON NOT NULL, ai_description TEXT DEFAULT NULL, ai_title VARCHAR(255) DEFAULT NULL, ai_country VARCHAR(128) DEFAULT NULL, ai_state VARCHAR(128) DEFAULT NULL, ai_city VARCHAR(128) DEFAULT NULL, ai_keywords JSON NOT NULL, enriched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enriched BOOLEAN DEFAULT NULL, prompt_tokens INT DEFAULT NULL, output_tokens INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE postcard_keyword (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(191) NOT NULL, confidence DOUBLE PRECISION DEFAULT NULL, basis TEXT DEFAULT NULL, postcard_id VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF74C39C83DD99C6 ON postcard_keyword (postcard_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_postcard_keyword ON postcard_keyword (postcard_id, value)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE postcard_keyword ADD CONSTRAINT FK_BF74C39C83DD99C6 FOREIGN KEY (postcard_id) REFERENCES postcard (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE postcard_keyword DROP CONSTRAINT FK_BF74C39C83DD99C6');
        $this->addSql('DROP TABLE ai_batch');
        $this->addSql('DROP TABLE ai_batch_result');
        $this->addSql('DROP TABLE batch_run');
        $this->addSql('DROP TABLE postcard');
        $this->addSql('DROP TABLE postcard_keyword');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
